# This is a basic workflow to help you get started with Actions

name: SCV-IaC-State_TF-Apply
env:
  #TFSTATE_ID: 50694
  AWSENV: 'dev'
  AWS_REGION: 'ap-southeast-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - 'release'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  tf-apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # runs within your Docker container
    container:
      image: docker://cg5labs/my-alpine:latest    # checkout your code from your repository
    
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
 
    - name: Terraform init
      run: |
          cd "${GITHUB_WORKSPACE}/scv-iac-state" && \
          /usr/bin/terraform init

    - name: Terraform apply
      run: | 
          cd "${GITHUB_WORKSPACE}/scv-iac-state" && \
          /usr/bin/terraform  \
            apply -auto-approve

    - name: Terraform init -force-copy
      run: |
          cd "${GITHUB_WORKSPACE}/scv-iac-state" && \
          /usr/bin/terraform  \
            init force-copy 

    - name: Terraform output to file
      run: |
          cd "${GITHUB_WORKSPACE}/scv-iac-state" && \
          /usr/bin/terraform  \
            output -json > tf_output.json
          tar -cvf ../s3_backend_custom_config.tar ./backend-*.tf
          tar -uvf ../s3_backend_custom_config.tar ./tf_output.json

    - name: Upload s3_backend_custom_config.tar
      uses: actions/upload-artifact@v2
      with:
        name: s3_backend_custom_config.tar
        path: s3_backend_custom_config.tar

            
